import { type ApiConfig, type Variant, type ComparisonData, type ExtractedSpecs, type ConsolidatedDocs, type LowLevelExtraction, type MidLevelSynthesis, type HighLevelIntent, type NormalizationResult, type ValidationReport, type Workspace } from '../types';

export async function performApiCall(prompt: string, apiConfig: ApiConfig, expectJson: boolean = true): Promise<any> {
  const { provider, apiKey, model } = apiConfig;

  const body: { [key: string]: any } = {
      model,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.2,
      max_tokens: 4000,
  };

  if (expectJson) {
      body.response_format = { type: "json_object" };
  }

  let lastError: any = null;
  const retries = 2; // Total attempts = 3

  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      // Call the backend proxy
      const response = await fetch('/api/llm', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          provider,
          apiKey,
          body
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error?.message || `API request failed with status ${response.status}`);
      }

      const data = await response.json();
      const content = data.choices[0].message.content;
      
      if (expectJson) {
          try {
            // Attempt to clean the content if LLM included markdown wrappers
            const cleanedContent = content.trim().replace(/^```json\n?/, '').replace(/\n?```$/, '');
            return JSON.parse(cleanedContent);
          } catch (e) {
            console.warn(`Attempt ${attempt + 1}/${retries + 1} failed to parse JSON. Content sub: ${content.substring(0, 100)}...`);
            lastError = e;
            if (attempt < retries) continue; // Try again
            return { raw: content, parseError: true }; 
          }
      } else {
        return content;
      }
    } catch (err) {
      lastError = err;
      if (attempt < retries) {
        // Add a delay before retry
        await new Promise(resolve => setTimeout(resolve, 1000 * (attempt + 1)));
        continue;
      }
      throw err;
    }
  }
  
  throw lastError || new Error("API call failed after retries");
}

// Pass 0: Repository Summary
export const runRepositorySummary = async (variant: Variant, apiConfig: ApiConfig): Promise<string> => {
    // Phase 4.3 - CCC Integration preferred path
    if (variant.hasCCC && variant.cccArtifacts?.llmMd) {
        const cccContext = [
          variant.cccArtifacts.llmMd,
          variant.cccArtifacts.publicApi || '',
          variant.cccArtifacts.capabilities || '',
        ].join('\n\n---\n\n');

        const prompt = `
Analyze this pre-compiled context for a codebase (generated by CCC — Code Context Compiler).
Provide a concise high-level summary of the application's purpose, key technologies, and architecture.
Respond as JSON: { "summary": "..." }

CCC Context:
${cccContext.substring(0, 15000)}
        `;
        const result = await performApiCall(prompt, apiConfig);
        return result.summary || 'Failed to generate summary from CCC artifacts.';
    }

    let files: { [key: string]: string } = {};
    try {
        files = JSON.parse(variant.rawContent);
    } catch(e) {
        console.error("Could not parse variant rawContent as JSON for repository summary.");
        return variant.rawContent; // Fallback to raw content if not a file map
    }

    // Call /api/compress first (Phase 1.2)
    let skeletonContent = "";
    try {
        const compressRes = await fetch('/api/compress', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ files }),
        });
        if (compressRes.ok) {
            const compressed = await compressRes.json();
            skeletonContent = compressed.skeleton;
        }
    } catch (e) {
        console.warn("Server side compression failed, falling back to substring truncation.", e);
    }

    if (!skeletonContent) {
        const fileList = Object.keys(files).map(path => {
            const content = files[path];
            const truncatedContent = content.substring(0, 1000); 
            return `### File: ${path}\n\`\`\`\n${truncatedContent}\n\`\`\``;
        }).join('\n\n');
        skeletonContent = fileList.substring(0, 20000);
    }

    const prompt = `
    Analyze the following repository structure and file contents. Provide a concise, high-level summary that captures the application's main purpose, key technologies or frameworks used, and overall architecture. This summary will be used as input for a more detailed analysis later.
    Focus on creating a holistic overview, not a file-by-file description.
    Respond with a single JSON object with one key: "summary", containing the text summary.

    Repository Content:
    ${skeletonContent}
    `;

    const result = await performApiCall(prompt, apiConfig);
    return result.summary || `Failed to generate repository summary for ${variant.name}.`;
};


// Pass 1: Low-Level Extraction
export const runLowLevelExtraction = async (content: string, variant: Variant, apiConfig: ApiConfig): Promise<LowLevelExtraction> => {
    // Phase 4.3 - CCC Integration preferred path
    if (variant.hasCCC && variant.cccArtifacts) {
        // CCC already did the low-level extraction deterministically
        return {
            rawFeatures: variant.cccArtifacts.publicApi || 'Refer to publicApi metadata.',
            modules: variant.cccArtifacts.capabilities || 'Refer to capabilities metadata.',
            patterns: variant.cccArtifacts.dependencyGraph || 'Refer to dependencyGraph metadata.',
            fileLevelSummary: variant.cccArtifacts.llmMd || 'Refer to llmMd summary.'
        };
    }

    let files: { [key: string]: string } = {};
    try {
        files = JSON.parse(variant.rawContent);
    } catch(e) {
        // Fallback if not a valid file map JSON string
    }

    let skeletonContent = content;
    if (Object.keys(files).length > 0) {
        try {
            const compressRes = await fetch('/api/compress', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ files }),
            });
            if (compressRes.ok) {
                const compressed = await compressRes.json();
                skeletonContent = compressed.skeleton;
            }
        } catch (e) {
            console.warn("Server side compression failed inside Pass 1.", e);
        }
    }

    const prompt = `
    Analyze the following application code/specification. Extract raw, low-level details.
    Respond with a valid JSON object with the following keys: "rawFeatures", "modules", "patterns", "fileLevelSummary".
    
    - rawFeatures: (string) A detailed list of all user-facing features found in the code.
    - modules: (string) A list of the key files, components, or code modules.
    - patterns: (string) A list of any identified coding paradigms or architectural patterns (e.g., MVC, Singleton, Observer).
    - fileLevelSummary: (string) A brief, technical summary of the code's primary purpose.

    Application Name: ${variant.name}
    Content:
    \`\`\`
    ${skeletonContent.substring(0, 15000)}
    \`\`\`
    `;
    return performApiCall(prompt, apiConfig);
};

// Pass 2: Mid-Level Synthesis
export const runMidLevelSynthesis = async (lowLevelResult: LowLevelExtraction, variant: Variant, apiConfig: ApiConfig): Promise<MidLevelSynthesis> => {
    const prompt = `
    Given the low-level analysis of an application, synthesize it into mid-level concepts.
    Respond with a valid JSON object with keys: "functionalGroups", "subsystems".

    - functionalGroups: (string) Group the raw features into logical categories or user workflows (e.g., "User Authentication", "Data Visualization", "Admin Panel").
    - subsystems: (string) Identify the major subsystems or high-level architectural components (e.g., "Frontend Client", "API Gateway", "Database Service").

    Low-Level Analysis of ${variant.name}:
    ${JSON.stringify(lowLevelResult)}
    `;
    return performApiCall(prompt, apiConfig);
};

// Pass 3: High-Level Intent Reconstruction
export const runHighLevelIntent = async (midLevelResult: MidLevelSynthesis, variant: Variant, apiConfig: ApiConfig): Promise<HighLevelIntent> => {
    const prompt = `
    From the mid-level synthesis of an application, reconstruct its high-level design intent and philosophy.
    Respond with a valid JSON object with keys: "designPhilosophy", "architecturalApproach", "dataDesignIntentions", "implicitBusinessLogic", "constraintsAndTradeoffs".

    - designPhilosophy: (string) Describe the core design goal (e.g., "User-centric and highly interactive", "Data-driven with a focus on performance").
    - architecturalApproach: (string) Define the overall architecture (e.g., "Monolithic SPA", "Micro-frontend architecture", "Server-side rendered application").
    - dataDesignIntentions: (string) Explain the purpose and structure of the data model.
    - implicitBusinessLogic: (string) Infer and describe any key business rules or logic not explicitly stated.
    - constraintsAndTradeoffs: (string) Identify any apparent technical constraints or design trade-offs made.

    Mid-Level Synthesis of ${variant.name}:
    ${JSON.stringify(midLevelResult)}
    `;
    return performApiCall(prompt, apiConfig);
};

// Pass 4: Final Specification Build
export const runFinalSpecBuild = async (pipelineResults: ExtractedSpecs['pipelineResults'], variant: Variant, apiConfig: ApiConfig): Promise<Omit<ExtractedSpecs, 'pipelineResults' | 'repositorySummary'>> => {
    const prompt = `
    Based on the complete hierarchical analysis (low, mid, and high level), generate a final, polished specification.
    Respond with a valid JSON object with the following keys: "functional", "architecture", "dataModel", "apiEndpoints", "strengths", "weaknesses", "notes".
    
    - functional: (string) A detailed, well-structured description of key features and capabilities.
    - architecture: (string) The technical structure, patterns, and frameworks used.
    - dataModel: (string) An explanation of entities, relationships, and schemas.
    - apiEndpoints: (string) A description of the API endpoints. If none, state "Not applicable".
    - strengths: (string[]) An array of key strengths.
    - weaknesses: (string[]) An array of key weaknesses.
    - notes: (string) Any other important implementation details.

    Full Analysis of ${variant.name}:
    ${JSON.stringify(pipelineResults)}
    `;
    return performApiCall(prompt, apiConfig);
};


export const compareVariants = async (variants: Variant[], apiConfig: ApiConfig): Promise<ComparisonData> => {
    const prompt = `
    Perform a semantic comparison of the following application variants based on their extracted Knowledge Artifacts.
    Identify:
    - Shared artifacts across variants.
    - Differences in implementations and designs for similar artifacts.
    - Architectural improvements and recommendations.
    
    Respond with a valid JSON object with keys: "featureMatrix", "architectureDiff", "dataModelDiff", "recommendations", "tradeoffs".

    - featureMatrix: (string) A markdown table comparing key Knowledge Artifacts and capabilities across variants.
    - architectureDiff: (string) A detailed summary comparing the architectural approaches, patterns, decisions, and system boundaries mapped out by the artifacts.
    - dataModelDiff: (string) A comparison of the entities, data layouts, and data design intentions discovered.
    - recommendations: (string) Actionable recommendations on which artifacts to merge (e.g. "Merge auth, keep React UI"), which to evolve, and which to deprecate or discard.
    - tradeoffs: (string) A list of key tradeoffs and architectural decisions required for the consolidated master model.

    Discovered Knowledge Artifacts for each Variant:
    ${variants.map(v => `
    ## Variant Name: ${v.name}
    Artifacts Discovered:
    ${JSON.stringify((v.knowledgeArtifacts || []).map(a => ({
      id: a.id,
      type: a.type,
      name: a.name,
      purpose: a.purpose,
      maturity: a.metrics.maturity,
      reusePotential: a.metrics.reusePotential
    })), null, 2)}
    `).join('\n')}
    `;
    return performApiCall(prompt, apiConfig);
};

export const detectAndNormalize = async (variants: Variant[], comparison: ComparisonData, apiConfig: ApiConfig): Promise<NormalizationResult> => {
    const prompt = `
    As a senior system architect, your task is to analyze the provided application variants and their comparison report to identify conflicts and create a harmonized, normalized model for a new, unified application.

    Respond with a valid JSON object with the following keys: "conflicts", "harmonizedDomainModel", "normalizedModules", "notes".

    1.  **conflicts**: An array of conflict objects. For each conflict, identify:
        *   \`area\`: (enum: 'Data Model', 'API', 'UX Flow', 'Naming Convention', 'Architecture', 'Other') The category of the conflict.
        *   \`description\`: (string) A clear and concise explanation of the conflict.
        *   \`variantsInvolved\`: (string[]) An array of the names of the variants that exhibit this conflict.
        *   \`recommendation\`: (string) A specific, actionable recommendation for resolving the conflict in the unified app.

    2.  **harmonizedDomainModel**: (string) Based on your conflict analysis, describe a clean, unified domain model (entities, relationships, and key attributes) for the final application. This should be in markdown format.

    3.  **normalizedModules**: (string) Propose a high-level, normalized module or component structure for the final application. This should be in markdown format.

    4.  **notes**: (string) Any other critical observations or strategic advice for the consolidation process.

    ## Variants Summary:
    ${variants.map(v => `${v.name}: ${JSON.stringify(v.extractedSpecs).substring(0, 1500)}`).join('\n')}

    ## Comparison Analysis:
    ${JSON.stringify(comparison).substring(0, 2000)}
    `;
    return performApiCall(prompt, apiConfig);
};


export const consolidateSpecifications = async (variants: Variant[], comparison: ComparisonData, normalization: NormalizationResult, apiConfig: ApiConfig): Promise<ConsolidatedDocs> => {
    const prompt = `
    Create a consolidated master specification from the provided application variants, comparison analysis, and the crucial normalization report.
    The master specification must be generated from the Semantic Model (the combined Knowledge Artifacts of all variants).
    Generate complete documentation for each section.
    Respond with a valid JSON object with the following keys: "prd", "architecture", "modules", "dataModel", "decisions", "migration", "provenance".
    
    - prd: (string) A full Product Requirements Document (PRD) driven by the discovered capabilities and products in markdown.
    - architecture: (string) A detailed System Architecture document based on the harmonized model, patterns, and component registry in markdown.
    - modules: (string) A breakdown of the system into modular packages, reflecting the promoted component and service artifacts in markdown.
    - dataModel: (string) A specification for the unified data model, based on the harmonized model in markdown.
    - decisions: (string) A log of key architectural and design decisions made, mapping to documented decision artifacts in markdown.
    - migration: (string) A high-level implementation and migration roadmap in markdown.
    - provenance: (array) An array of provenance entries tracking sections or key architectural decisions back to their origin. Each entry must follow this schema:
      {
        "section": "Section or requirement name (e.g. prd, architecture, dataModel)",
        "sourceVariant": "Name of the source variant",
        "originalFile": "Approximate file path or component name in that variant (e.g. src/auth.ts)",
        "justification": "Why this implementation, artifact, or requirement was promoted and merged",
        "confidence": 0.95 // Number between 0.0 and 1.0 representing mapping certainty
      }

    ## Semantic Model (Knowledge Artifacts from all Variants):
    ${variants.map(v => `
    ### Variant: ${v.name}
    Artifacts:
    ${JSON.stringify((v.knowledgeArtifacts || []).map(a => ({
      id: a.id,
      type: a.type,
      name: a.name,
      purpose: a.purpose,
      maturity: a.metrics.maturity,
      reusePotential: a.metrics.reusePotential
    })), null, 2)}
    `).join('\n')}

    ## Comparison Analysis:
    ${JSON.stringify(comparison).substring(0, 1500)}
    
    ## CRITICAL: Normalization and Harmonization Report:
    ${JSON.stringify(normalization).substring(0, 2500)}
    `;
    return performApiCall(prompt, apiConfig);
};

export const generateVisualsAndBlueprint = async (docs: ConsolidatedDocs, apiConfig: ApiConfig): Promise<Pick<ConsolidatedDocs, 'architectureDiagrams' | 'implementationBlueprint'>> => {
  const prompt = `
  As a senior software architect, your task is to generate visual architecture diagrams and a practical implementation blueprint based on the provided consolidated documentation.
  Respond with a single, valid JSON object with two top-level keys: "architectureDiagrams" and "implementationBlueprint".

  1. **architectureDiagrams**: An object containing Mermaid.js syntax for the following diagrams. If a diagram is not applicable, omit the key.
      - "knowledgeHierarchical": (string) A visual top-down hierarchical Knowledge Artifact Map (Mermaid graph TD) showing the mapping from Products -> Capabilities -> Components/Services -> Concrete Implementations.
      - "c4": (string) A C4 Container diagram showing the main components and their interactions.
      - "sequence": (string) A sequence diagram for a primary user flow described in the PRD.
      - "schema": (string) An Entity-Relationship Diagram (ERD) representing the harmonized data model.

  2. **implementationBlueprint**: An object containing code and structure for the new application.
      - "folderStructure": (string) A text-based tree view of the recommended folder structure.
      - "packageJson": (string) The content for a package.json file, including recommended dependencies.
      - "typeDefinitions": (string) Key TypeScript interfaces or types based on the data model.
      - "apiSkeletons": (string) Skeleton code for primary API endpoints or services.

  ## Consolidated Documentation:
  ### PRD:
  ${docs.prd?.substring(0, 2000)}

  ### System Architecture:
  ${docs.architecture?.substring(0, 2000)}

  ### Data Model:
  ${docs.dataModel?.substring(0, 2000)}
  `;

  return performApiCall(prompt, apiConfig);
};

export const runRoundTripValidation = async (docs: ConsolidatedDocs, variants: Variant[], apiConfig: ApiConfig): Promise<ValidationReport> => {
  const prompt = `
  As a meticulous QA engineer, your task is to perform a "round-trip validation" to ensure no critical requirements were lost during the consolidation of multiple application variants into a single specification.
  Compare the final consolidated documentation against the extracted specifications of the original variants.

  Respond with a valid JSON object with two keys: "summary" and "findings".

  1. **summary**: (string) A brief, high-level summary of your validation findings.
  
  2. **findings**: An array of finding objects. For each significant discrepancy or confirmation, create an object with the following structure:
     * \`variant\`: (string) The name of the original variant the finding relates to.
     * \`area\`: (string) The area of the specification (e.g., "User Authentication", "Core Feature X", "Data Model").
     * \`finding\`: (string) A clear description of what you found.
     * \`type\`: (enum: "lost", "misrepresented", "confirmed")
       - "lost": A feature/requirement from the original variant is completely missing in the final spec.
       - "misrepresented": A feature/requirement is present but its details or intent have been significantly altered.
       - "confirmed": A key feature has been successfully and accurately merged.

  ## Final Consolidated Documentation:
  ### PRD:
  ${docs.prd?.substring(0, 4000)}
  ### Architecture:
  ${docs.architecture?.substring(0, 4000)}

  ## Original Variant Specifications:
  ${variants.map(v => `
  ### Variant: ${v.name}
  ${JSON.stringify(v.extractedSpecs).substring(0, 2000)}
  `).join('\n')}
  `;

  return performApiCall(prompt, apiConfig);
};

export const runQAndA = async (
  question: string, 
  workspace: { 
    variants: Variant[], 
    comparison: ComparisonData | null, 
    normalization: NormalizationResult | null, 
    docs: ConsolidatedDocs | null 
  },
  apiConfig: ApiConfig
): Promise<string> => {
  const context = `
  You are an expert software architect AI assistant. Your task is to answer questions based *only* on the provided context about a software project. Do not invent information or provide advice beyond the scope of the context. If the answer is not in the context, state that clearly.

  ## Project Context ##

  ### Original Variants Specifications:
  ${workspace.variants.map(v => `
  #### Variant: ${v.name}
  ${JSON.stringify(v.extractedSpecs).substring(0, 1500)}
  `).join('\n')}

  ### Comparison & Normalization Report:
  ${JSON.stringify(workspace.comparison).substring(0, 1500)}
  ${JSON.stringify(workspace.normalization).substring(0, 1500)}

  ### Final Consolidated Documentation:
  ${JSON.stringify(workspace.docs).substring(0, 3000)}

  ## User's Question ##
  Based *only* on the context provided above, answer the following question:
  "${question}"
  `;

  const response = await performApiCall(context, apiConfig, false);
  return response;
};
